version: "{build}"

image: Visual Studio 2017

configuration:
  - Debug

platform:
  - x64

matrix:
  fast_finish: true

environment:
  matrix:
    - PYTHON: "C:\\Python37"

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%;
  - cmd: python --version
  - cmd: where pip.exe
  - cmd: python -m pip install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: choco install ninja

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Visual Studio 15 2017" -A x64

build_script:
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: ctest -C %CONFIGURATION%
test_script:
  - cmd: cd ..
  - cmd: curl -L0 https://github.com/kward/shunit2/archive/v2.1.7.zip --output shunit2.zip
  - cmd: unzip -j -n shunit2.zip
  - cmd: bash ./test/installation-tests.sh
