name: Continuous Benchmark
on:
  push:

jobs:
  benchmark:
    name: Run SI benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo -H pip3 install setuptools wheel
          sudo -H pip3 install conan
          conan profile detect --force
          sudo apt-get install -y ninja-build

      - name: Build and run benchmarks with Catch2
        run: |
          conan install . --output-folder=build --build=missing --settings=build_type=Release
          cmake --preset=ci-ninja-release
          cmake --build build --target SI_unit_benchmarks
          ./build/test/SI_unit_benchmarks | tee ./build/benchmark_result.txt
      - name: Store benchmark result
        if: github.ref == 'refs/heads/main'
        uses: rhysd/github-action-benchmark@v1.7.0
        with:
          name: Catch2 Benchmark
          tool: "catch2"
          output-file-path: build/benchmark_result.txt
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@bernedom"
      - name: Run benchmark - no store
        if: github.ref != 'refs/heads/main'
        uses: rhysd/github-action-benchmark@v1.7.0
        with:
          name: Catch2 Benchmark
          tool: "catch2"
          output-file-path: build/benchmark_result.txt
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: false
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@bernedom"
